# BlueDwarf tunnel appveyor.yml script

version: '{branch}-{build}'

branches:
  only:
    - master

before_build:
  nuget restore

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

configuration: Release
platform: Any CPU

build:
  parallel: true   
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal

environment:
  pfxKey:
    secure: 7kj0HlKk9INPLkabdbsdKp6R2i8BvgBzj03hzqUbLuU=

after_test:
  - ps: $pfxKeyS = ConvertTo-SecureString $env:pfxKey -AsPlainText -Force
  - ps: Import-PfxCertificate -FilePath Tools\490fc8e027f9320a04d00960ce799809.pfx cert:\CurrentUser\My -Password $pfxKeyS
  - msbuild /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /t:Publish /property:ApplicationRevision=%APPVEYOR_BUILD_NUMBER%
  - ps: $root = Resolve-Path .\BlueDwarf\bin\Release\app.publish; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName ClickOnce }

artifacts:
  - path: '.\BlueDwarf\bin\Release\BlueDwarf.exe'
    name: exe

deploy:
  - provider: NuGet
    api_key:
      secure: rEYnR9JThbc6x8DdCo1K8+fgsGKzjNKzTZsldXFLYMm/tFPC7JWWvuKpVTrDBd+g
    skip_symbols: false

  - provider: FTP
    protocol: sftp
    host: openstore.craponne.fr:2304
    username: openstore
    password:
      secure: /Yr9Wtf5W7SfwBuz/LYLPN+aaxzjPjtIpfzLloth97U=
    folder: ~/openstore.arxone.com
    artifact: ClickOnce exe
